version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo "installing something"
    pre_build:
        commands:
            - echo "we are in the pre building"
    build:
        commands:
            - echo "we are in building"
            - npm build
    post_build:
        commands:
            - echo "we are in post build phase"
